In [1]:
import pandas as pd
import numpy as np

In [2]:
ch1 = pd.read_csv("CH1.csv")

In [3]:
ch1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2617 entries, 0 to 2616
Columns: 5003 entries, ID to label
dtypes: float64(5001), int64(1), object(1)
memory usage: 99.9+ MB


In [4]:
X = ch1.select_dtypes(exclude = "int64")
Y = ch1["label"]

### Data Analysis

#### Labels Histogram

In [5]:
pd.value_counts(Y)

3    387
1    382
2    379
4    377
5    375
6    364
0    353
Name: label, dtype: int64

In [6]:
fft = X.select_dtypes("float64").T

##### Files with infinity components

In [7]:
ch1.loc[np.where(np.max(fft) == np.inf)[0], "ID"]

55      0_c2319c35c100.csv
1169    3_c1617c35c100.csv
1338    3_c1934c50c100.csv
1915    5_c0849c30c000.csv
1925    5_c0859c30c000.csv
1926    5_c0860c30c000.csv
1927    5_c0861c30c000.csv
2107    5_c1248c50c050.csv
2108    5_c1249c50c050.csv
2109    5_c1250c50c050.csv
2110    5_c1251c50c050.csv
2111    5_c1252c50c050.csv
2112    5_c1253c50c050.csv
2113    5_c1254c50c050.csv
Name: ID, dtype: object

In [8]:
finite_X = X.drop(np.where(np.max(fft) == np.inf)[0])
finite_Y = Y.drop(np.where(np.max(fft) == np.inf)[0])

In [9]:
finite_X.iloc[np.where(finite_X.isna().any(axis = 1))[0]]

ID   0   1   2   3   4   5   6   7   8  ...  4991  4992  \
835   2_c0946c35c000.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   
1301  3_c1865c45c050.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   
1302  3_c1866c45c050.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   
1312  3_c1876c45c050.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   
1563  4_c0135c35c100.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   
1992  5_c1006c40c100.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   
2117  5_c1258c50c050.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   
2146  5_c1321c55c100.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   
2184  5_c1392c55c000.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   
2387  6_c1814c40c000.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   
2397  6_c1824c40c000.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   
2417  6_c1862c45c100.csv NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN   NaN   

      4993  4994  4995  4996  4997  4998  4999  5000  
835    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
1301   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
1302   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
1312   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
1563   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
1992   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2117   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2146   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2184   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2387   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2397   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2417   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[12 rows x 5002 columns]

In [10]:
finite_Y = finite_Y.drop(np.where(finite_X.isna().any(axis = 1))[0])
finite_X = finite_X.drop(np.where(finite_X.isna().any(axis = 1))[0])

In [11]:
finite_X = finite_X.reset_index(drop=True)
finite_Y = finite_Y.reset_index(drop=True)

In [12]:
finite_X

ID         0         1         2         3         4  \
0     0_c2264c30c100.csv  1.624898  0.000098  0.000067  0.000717  0.000031   
1     0_c2265c30c100.csv  1.624795  0.000019  0.000071  0.000718  0.000005   
2     0_c2266c30c100.csv  1.624771  0.000038  0.000072  0.000653  0.000041   
3     0_c2267c30c100.csv  1.620564  0.000041  0.000044  0.000353  0.000069   
4     0_c2268c30c100.csv  1.620967  0.000063  0.000062  0.000350  0.000037   
...                  ...       ...       ...       ...       ...       ...   
2586  6_c2259c60c000.csv  1.603394  0.000095  0.000057  0.000046  0.000019   
2587  6_c2260c60c000.csv  1.603403  0.000022  0.000073  0.000099  0.000046   
2588  6_c2261c60c000.csv  1.603343  0.000076  0.000043  0.000039  0.000018   
2589  6_c2262c60c000.csv  1.603901  0.000032  0.000019  0.000109  0.000045   
2590  6_c2263c60c000.csv  1.604187  0.000056  0.000026  0.000065  0.000022   

             5         6         7         8  ...      4991      4992  \
0     0.000052  0.000010  0.000006  0.000055  ...  0.000016  0.000049   
1     0.000028  0.000038  0.000012  0.000019  ...  0.000019  0.000050   
2     0.000057  0.000050  0.000036  0.000044  ...  0.000022  0.000043   
3     0.000074  0.000028  0.000010  0.000035  ...  0.000018  0.000053   
4     0.000048  0.000011  0.000039  0.000040  ...  0.000052  0.000022   
...        ...       ...       ...       ...  ...       ...       ...   
2586  0.000068  0.000059  0.000025  0.000044  ...  0.000074  0.000026   
2587  0.000096  0.000031  0.000061  0.000044  ...  0.000049  0.000024   
2588  0.000096  0.000090  0.000048  0.000068  ...  0.000027  0.000029   
2589  0.000044  0.000036  0.000085  0.000083  ...  0.000047  0.000057   
2590  0.000039  0.000043  0.000102  0.000052  ...  0.000024  0.000056   

          4993      4994      4995      4996      4997      4998      4999  \
0     0.000058  0.000038  0.000025  0.000011  0.000054  0.000027  0.000030   
1     0.000048  0.000034  0.000012  0.000012  0.000057  0.000039  0.000032   
2     0.000041  0.000028  0.000025  0.000018  0.000018  0.000043  0.000015   
3     0.000023  0.000011  0.000014  0.000033  0.000081  0.000029  0.000054   
4     0.000004  0.000014  0.000043  0.000026  0.000050  0.000037  0.000036   
...        ...       ...       ...       ...       ...       ...       ...   
2586  0.000032  0.000033  0.000054  0.000049  0.000026  0.000041  0.000028   
2587  0.000018  0.000031  0.000043  0.000037  0.000085  0.000017  0.000077   
2588  0.000047  0.000055  0.000032  0.000015  0.000077  0.000021  0.000020   
2589  0.000036  0.000023  0.000060  0.000078  0.000059  0.000025  0.000039   
2590  0.000052  0.000051  0.000057  0.000032  0.000019  0.000053  0.000046   

              5000  
0     6.080000e-06  
1     6.000000e-06  
2     3.900000e-05  
3     6.400000e-05  
4     1.990000e-05  
...            ...  
2586  3.340000e-05  
2587  2.040000e-05  
2588  6.250000e-07  
2589  4.340000e-05  
2590  2.090000e-05  

[2591 rows x 5002 columns]

### Data Prep

In [13]:
from sklearn.model_selection import train_test_split

clean_X = finite_X.drop(["0", "ID"], axis = 1)

clean_X = clean_X.reset_index(drop=True)

x_train, x_test, y_train, y_test = train_test_split(clean_X, finite_Y, test_size=0.2, random_state=0, stratify=finite_Y)

In [14]:
x_train.shape

(2072, 5000)

In [15]:
np.max(x_train)

1       0.001310
2       0.001854
3       0.001569
4       0.001676
5       0.001486
          ...   
4996    0.000173
4997    0.000171
4998    0.000198
4999    0.000159
5000    0.000270
Length: 5000, dtype: float64

In [16]:
n_train = np.reshape(np.linalg.norm(x_train, axis = 1), (-1, 1))
n_test = np.reshape(np.linalg.norm(x_test, axis = 1), (-1,1))

In [17]:
normalized_x_train = (x_train / n_train) * 100
normalized_x_test = (x_test / n_test) * 100

In [18]:
np.max(normalized_x_train)

1       3.505910
2       3.344163
3       2.740726
4       3.177275
5       2.171519
          ...   
4996    0.339556
4997    0.548621
4998    0.782697
4999    0.430526
5000    0.619925
Length: 5000, dtype: float64

In [19]:
np.max(normalized_x_test)

1       2.974812
2       1.828941
3       2.129928
4       1.607765
5       1.700671
          ...   
4996    0.233520
4997    0.265578
4998    0.309125
4999    0.248961
5000    0.450793
Length: 5000, dtype: float64

In [20]:
y_train = np.reshape(np.array(y_train), (-1,1))
y_test = np.reshape(np.array(y_test), (-1,1))

In [21]:
from sklearn.preprocessing import OneHotEncoder

o = OneHotEncoder()
y_train_onehot = o.fit_transform(y_train).toarray()
y_test_onehot = o.transform(y_test).toarray()

### Model Building starts

In [22]:
import tensorflow as tf

from keras.layers import Dense
from keras import Sequential
from keras.losses import SparseCategoricalCrossentropy, CategoricalCrossentropy

In [32]:
model = Sequential([Dense(2500, activation = "sigmoid"),
                   Dense(100, activation = "sigmoid"),
                   Dense(7, activation = "softmax")])

model.compile(loss=CategoricalCrossentropy(), optimizer = "rmsprop",metrics=["accuracy"])

In [34]:
model.predict(x_test)

17/17 [==============================] - 0s 7ms/step


array([[0.10190462, 0.07163243, 0.15777762, ..., 0.07533365, 0.23508085,
        0.33563754],
       [0.10190777, 0.07163311, 0.1577277 , ..., 0.07536296, 0.23515363,
        0.335581  ],
       [0.10189758, 0.0716022 , 0.1576818 , ..., 0.07538538, 0.23524109,
        0.3355728 ],
       ...,
       [0.10188042, 0.07162366, 0.15773423, ..., 0.07533796, 0.23514584,
        0.3356496 ],
       [0.10185643, 0.0716631 , 0.15775527, ..., 0.07529704, 0.23516025,
        0.33563638],
       [0.10188197, 0.07161187, 0.15777853, ..., 0.075376  , 0.23509602,
        0.33562395]], dtype=float32)

In [35]:
newWeights = []

for l in model.get_weights():
    print(l.shape)
    try:
        x = l.shape[1]
        newWeights += [0.35  + 0.1 * np.random.randn(l.shape[0], x)]
    except:
        newWeights += [np.full(l.shape[0], 0.25)]
newWeights

(5000, 2500)
(2500,)
(2500, 100)
(100,)
(100, 7)
(7,)


[array([[0.35464923, 0.2415142 , 0.36248665, ..., 0.14954351, 0.36651519,
         0.43847486],
        [0.31383564, 0.43861906, 0.16758593, ..., 0.4636918 , 0.28844836,
         0.46040925],
        [0.34142035, 0.39500593, 0.32706061, ..., 0.45318737, 0.56903419,
         0.46555014],
        ...,
        [0.13738802, 0.27352045, 0.46800889, ..., 0.26338609, 0.35397018,
         0.51098508],
        [0.26697879, 0.22374126, 0.23099966, ..., 0.23164316, 0.54216186,
         0.36455542],
        [0.32026332, 0.58787947, 0.31149557, ..., 0.23090465, 0.19700003,
         0.40449016]]),
 array([0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25]),
 array([[0.41244436, 0.28569978, 0.29768374, ..., 0.33893893, 0.33516935,
         0.48481219],
        [0.32092689, 0.24539811, 0.18764038, ..., 0.28978145, 0.44755231,
         0.40267168],
        [0.45711628, 0.36502451, 0.28718719, ..., 0.56344766, 0.39433483,
         0.44800396],
        ...,
        [0.2804895 , 0.30257702, 0.44381739, ..., 0.29411

In [36]:
model.set_weights(newWeights)
model.weights

[<tf.Variable 'dense_3/kernel:0' shape=(5000, 2500) dtype=float32, numpy=
 array([[0.35464922, 0.24151419, 0.36248666, ..., 0.14954351, 0.3665152 ,
         0.43847486],
        [0.31383565, 0.43861905, 0.16758592, ..., 0.4636918 , 0.28844836,
         0.46040925],
        [0.34142035, 0.39500594, 0.3270606 , ..., 0.45318738, 0.56903416,
         0.46555015],
        ...,
        [0.13738802, 0.27352044, 0.46800888, ..., 0.2633861 , 0.35397017,
         0.5109851 ],
        [0.2669788 , 0.22374126, 0.23099966, ..., 0.23164317, 0.5421619 ,
         0.36455542],
        [0.32026333, 0.5878795 , 0.31149557, ..., 0.23090465, 0.19700003,
         0.40449017]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(2500,) dtype=float32, numpy=array([0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25], dtype=float32)>,
 <tf.Variable 'dense_4/kernel:0' shape=(2500, 100) dtype=float32, numpy=
 array([[0.41244435, 0.28569978, 0.29768375, ..., 0.33893892, 0.33516935,
         0.4848122 ],
        [0.3209269

In [37]:
model.predict(x_test)

17/17 [==============================] - 0s 7ms/step


array([[0.18742418, 0.3251409 , 0.0303869 , ..., 0.08211039, 0.1602372 ,
        0.07924211],
       [0.18742418, 0.3251409 , 0.0303869 , ..., 0.08211039, 0.1602372 ,
        0.07924211],
       [0.18742418, 0.3251409 , 0.0303869 , ..., 0.08211039, 0.1602372 ,
        0.07924211],
       ...,
       [0.1874385 , 0.3250529 , 0.03035296, ..., 0.08216994, 0.16035402,
        0.07912945],
       [0.1874385 , 0.3250529 , 0.03035296, ..., 0.08216994, 0.16035402,
        0.07912945],
       [0.1874385 , 0.3250529 , 0.03035296, ..., 0.08216994, 0.16035402,
        0.07912945]], dtype=float32)

In [38]:
model.fit(normalized_x_train, y_train_onehot)
model.predict(x_test)

17/17 [==============================] - 0s 2ms/step


array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

In [39]:
model.weights

[<tf.Variable 'dense_3/kernel:0' shape=(5000, 2500) dtype=float32, numpy=
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(2500,) dtype=float32, numpy=array([nan, nan, nan, ..., nan, nan, nan], dtype=float32)>,
 <tf.Variable 'dense_4/kernel:0' shape=(2500, 100) dtype=float32, numpy=
 array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(100,) dtype=float32, numpy=
 array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, n